---
# tasks file for ansible-motd
- include_tasks: "{{ role_path }}/tasks/debian.yaml"
  when: ansible_os_family == "Debian"

# - include_tasks: redhat.yml
#   when: ansible_os_family == "RedHat"

# - name: Change MOTD of the server
#   copy:
#     src:
#     dest: /etc/motd
#     become: yes

- name: main | Configuring MOTD
  template:
    #src: "{{ role_path }}/motd"
    src: etc/motd.j2
    dest: /etc/motd
  become: true
