---
- name: remove user from dev machines
  hosts: [all]
  vars_prompt:
    - name: "username"
      prompt: "Enter the username for the user to delete"
      private: False
      confirm: False
      default: "test"
    - name: "remove_home"
      prompt: "Type 1 to remove the home directory of the user, 0 if not"
      private: False
      confirm: False
      default: "1"
  tasks:
    - name: remove the user if it exists
      ansible.builtin.user:
        name: "{{username}}"
        state: "absent"
        remove: true
      become: true
    - name: remove home files and directories
      file:
        state: "absent"
        path: "/home/{{username}}"
        # owner: 1000 # set your owner, group, and mode accordingly
        # group: 1000
        # mode: "0777"
      # with_items:
      # - absent
      # - directory
      when: "remove_home == '1'"
      # when: "remove_home|bool"
      become: true
