- name: Download and install gitleaks
  ansible.builtin.unarchive:
    src: https://github.com/zricethezav/gitleaks/releases/download/v8.15.3/gitleaks_8.15.3_linux_x64.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    mode: "0755"
    owner: root
    group: root
    include:
    - gitleaks
    creates: /usr/local/bin/gitleaks

